config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "articles#index"

  resources :articles do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
   validates :title,  presence: true
   validates :author,  presence: true
   validates :text,  presence: true, length: { minimum: 5 }

   has_many :comments, dependent: :destroy
      # dependent: :destroy means the comments related 
      # to the specific post in mention get deleted if the post does.
end

app/models/comment.rb
class Comment < ApplicationRecord
   validates :name,  presence: true
   validates :comment_body,  presence: true, length: { minimum: 5 }
   
   belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

   def new
      @article = Article.new()
   end

   def create
      @article = Article.new(article_params)

      if @article.save
         
         redirect_to @article
         
      else
         render 'new'
      end
   end

   def show
      @article = Article.find(params[:id])
   end

   def index
      @articles = Article.all
   end

   def edit
      @article = Article.find(params[:id])
   end

   def update
      @article = Article.find(params[:id])

      if @article.update(article_params)
         
         redirect_to @article
      else
         render 'edit'
      end
   end

   def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to articles_path
   end


   private
   def article_params
      params.require(:article).permit(:title,:author,:text)
   end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_action :get_article

   def index
      @comment = @article.comments
   end

   def new
      @comment = @article.comments.build
   end
   
   def create
      @comment = @article.comments.build(comment_params)
      
      if @comment.save
        redirect_to @article
      else
         render :new
      end
  end

  def destroy
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to @article
  end

  private
  def get_article
   @article = Article.find(params[:article_id])
  end

  def comment_params
   params.require(:comment).permit(:name, :comment_body, :article_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/application/_header.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light shadow d-flex justify-content-between px-5">
    
      <%= link_to articles_path, class: "ml-5 mt-0 mb-0 text-decoration-none d-flex justify-content-between align-items-center" do %>
            <%= image_tag "logo1.png", height: 40, class: "m-1 personal-logo" %>
            <h3 class="text-maroon px-3 ubuntu-font">Blog</h3>
      <% end %>
      
      <%= link_to 'New Blog', new_article_path, class: "btn btn-success shadow mr-1 mt-0 mb-0" %>
</nav>

app/views/articles/_form.html.erb
<%= form_with scope: :article, model: @article, local: true do |f| %>

<p>
<% if @article.errors.any? %>

   <div class="d-flex flex-wrap justify-content-center fixed-bottom m-5">      
         <% @article.errors.full_messages.each do |message| %>
            <div class="alert alert-danger m-3 " role="alert"><%= message %></div>
         <% end %>
   </div>
<% end %>
</p>

<div class="d-flex flex-row flex-wrap justify-content-center pt-5 mt-5">

      <div class="card m-3 shadow d-flex flex-column justify-content-between bg-light border-0" style="width: 50rem;">

         
            <div class="card-body d-flex flex-column justify-content-between">
               <%= f.text_field :title, placeholder: "Title", class: "text-center form-control mb-2" %>

               <%= f.text_field :author, placeholder: "Author", class: "text-center form-control mb-2" %>

               <%= f.text_area :text, placeholder: "Text", class: "text-center form-control mb-2" %>

            </div>
         
         <div class="d-flex flex-row justify-content-center m-3">
         
            <%= link_to 'Cancel', articles_path, class: "btn btn-danger mx-3 shadow text-decoration-none text-white " %>

            <%= f.submit 'Publish', class: "btn btn-success mx-3 shadow" %>
         
         </div>
      
      </div>

</div>

<% end %>

app/views/articles/edit.html.erb
<div data-controller="article-form">

<%= render "form" %>

</div>

app/views/articles/index.html.erb
<div class="d-flex flex-row flex-wrap justify-content-center pt-5 mt-5 off-white">
   
   <% @articles.reverse_each do |article| %>
      <div class="bg-light border-0 card m-4 shadow d-flex flex-column justify-content-between" style="width: 18rem; height: 15rem;">

         <%= link_to article_path(article), class: "text-decoration-none link-dark" do %>
            <div class="card-body d-flex flex-column justify-content-between" style="height: 10rem;">
               <h4 class="card-title border-bottom border-warning pb-1 ubuntu-font text-maroon"><%= article.title %></h4>
               <h6 class="card-subtitle mb-2 text-muted"><%= article.author %></h6>
               <p class="card-text"><%= article.text[0, 50]... %></p>
               <small class="card-text text-muted sm">(<%= article.created_at.utc.localtime.strftime('%d %b %Y %I:%M %p') %>)</small> 
            </div>
         
         <% end %>
         
         <div class="d-flex flex-row justify-content-end m-3">
               <button type="button" class="btn btn-outline-success btn-sm mx-0 border-0"><%= link_to '✏️', edit_article_path(article), class: "text-decoration-none text-white" %></button>
               <button type="button" class="btn btn-outline-danger btn-sm border-0"><%= link_to '❌', article_path(article), method: :delete, data: {confirm: 'Delete chosen blog PERMANENTLY?'}, class: "text-decoration-none text-white" %></button>
         </div>
      
      </div>
   <% end %>

</div>

app/views/articles/new.html.erb
<div data-controller="article-form">

<%= render "form" %>

</div>

app/views/articles/show.html.erb
<div class="d-flex flex-column flex-wrap justify-content-center align-items-center pt-5 mt-5 off-white">

      <div class="card m-3 shadow d-flex flex-column justify-content-between bg-light border-0" style="width: 50vw;">

         
            <div class="card-body d-flex flex-column justify-content-between text-center">
               <h4 class="card-title ubuntu-font text-maroon border-warning"><%= @article.title %></h4>
               <h6 class="card-subtitle mb-2 text-muted">By: <%= @article.author %></h6>
               <textarea class="card-text text-center bg-light border-0 border-top border-bottom border-warning " style="height: auto; overflow-x: hidden;"><%= @article.text%></textarea>
               <p class="card-text text-muted">Created: <%= @article.created_at.utc.localtime.strftime('%d %b %Y %I:%M %p') %></p> 
            </div>
         
         <div class="d-flex flex-row justify-content-center m-3">
               <button type="button" class="btn btn-outline-primary btn-sm border-0"><%= link_to '⬅️', articles_path, class: "text-decoration-none text-white" %></button>
               <button type="button" class="btn btn-outline-success btn-sm mx-2 border-0"><%= link_to '✏️', edit_article_path(@article), class: "text-decoration-none text-white" %></button>

                <button type="button" class="btn btn-outline-success btn-sm mx-2 border-0"><%= link_to '🗣️', new_article_comment_path(@article), class: "text-decoration-none text-white" %></button>

               <button type="button" class="btn btn-outline-danger btn-sm border-0"><%= link_to '❌', article_path(@article), method: :delete, data: {confirm: 'Delete chosen article PERMANENTLY?'}, class: "text-decoration-none text-white" %></button>
         </div>
      
      </div>



    <div class="m-3 d-flex flex-column justify-content-between off-white border-0" style="width: 50vw;">
        <div class="card-body d-flex flex-column justify-content-between text-center">
            <h6 class="card-title ubuntu-font text-maroon border-warning">
            <%= @article.comments.count %> 🗣️
            </h6>
            <%= render @article.comments %>
        </div>
    </div>


</div>

app/views/comments/_comment.html.erb
<div class="card m-3 shadow d-flex flex-column justify-content-between bg-light border-0 p-1">

   <div> <%= comment.comment_body %> </div>

   <div class="d-flex align-items-center justify-content-end">
      <span class="text-muted"> By: <%= comment.name %> </span>
      <button type="button" class="btn btn-outline-danger btn-sm border-0"><%= link_to '❌', [comment.article, comment], method: :delete, data: {confirm: 'Delete chosen comment PERMANENTLY?'}, class: "text-decoration-none text-white" %></button>
   </div>
</div>







          


      

app/views/comments/_form.html.erb
<%= form_with scope: :comment, model: [@article, @comment], local: true do |f| %>

<p>
<% if @comment.errors.any? %>

   <div class="d-flex flex-wrap justify-content-center fixed-bottom m-5">      
         <% @comment.errors.full_messages.each do |message| %>
            <div class="alert alert-danger m-3 " role="alert"><%= message %></div>
         <% end %>
   </div>
<% end %>
</p>

<div class="d-flex flex-row flex-wrap justify-content-center pt-5 mt-5">

  <div class="card m-3 shadow d-flex flex-column justify-content-between bg-light border-0" style="width: 50rem;">

    <div class="card-body d-flex flex-column justify-content-between text-center">
      <h4 class="card-title ubuntu-font text-maroon border-warning"><%= @article.title %></h4>
      <h6 class="card-subtitle mb-2 text-muted">By: <%= @article.author %></h6>
    </div>

    <div class="card-body d-flex flex-column justify-content-between">
        <%= f.text_field :name, placeholder: "Name", class: "text-center form-control mb-2" %>

        <%= f.text_area :comment_body, placeholder: "Comment", class: "text-center form-control mb-2" %>
    </div>

    <div class="d-flex flex-row justify-content-center m-3">
    
      <%= link_to 'Cancel', @article, class: "btn btn-danger mx-3 shadow text-decoration-none text-white " %>

      <%= f.submit 'Comment', class: "btn btn-success mx-3 shadow" %>  
    </div>

  </div>  

<% end %>

</div>

app/views/comments/new.html.erb
<div data-controller="comment-form">

<%= render "form" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogv2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body class="off-white">

    <%= render "header" %>

    <%= yield %>
  </body>

</html>